### ISSUE TITLE
FYI: Things 3 URL Scheme Available

### ISSUE THREAD

**Issue by philoserf** [amureki/things-cli#2]
Great news for automation! 🤖 

https://support.culturedcode.com/customer/en/portal/articles/2803573-things-url-scheme

**Comment by amureki** [comment]
@philoserf this is a great news! I'll take a look and try to implement this.
I was missing tagging and setting up projects/areas.

Thank you very much!

**Comment by amureki** [comment]
@philoserf 
I researched this a bit. 
In the end, using this feature I can only generate links to actual actions. So it is questionable if it will be really usable somehow.

**Comment by amureki** [comment]
Or just fall down to something like this 
`open things:///show?id=today` (in `subprocess`, for example).
Which only would work on a machine, where Things are installed.

**Comment by philoserf** [comment]
I imagine an api/cli  that wraps the uri scheme and executes those uri. I will create a small example over the coming weekend.

**Comment by amureki** [comment]
Yeah, this would work, if you have an app on the same machine.
I am using this in my small Alexa skill, where URI execution would not work. :(
But from the other side, CLI usage would become much more powerful and usable with those.

**Comment by amureki** [comment]
@philoserf hi Mark,
thanks for handling the issue.

I wanted to know if you got any new insights on the topic?

**Comment by philoserf** [comment]
I've explored a few ways to use the URL API from local code. It works. For working with a remote API see https://github.com/nicolai86/things-cloud-sdk

**Comment by amureki** [comment]
@philoserf thank you! I will check it out.
